version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: next-social
      MYSQL_ROOT_PASSWORD: 2000101abc
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
